package wechat.function.movie;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

public class MD_AutoRun {
	
	//final static int interval = 1 * 60 * 60 * 1000;
	final static int interval = 60 * 1000;
	final static int num = 0;
	
	public static void main(String[] args) {  
	        // TODO todo.generated by zoer  
	        Timer timer = new Timer();  
	        timer.schedule(new MyTask(), 1000, interval);  
	    }  
	}  
	  
	class MyTask extends TimerTask {  
		ArrayList<Object> movieList = new ArrayList<Object>();
		String currentFilePath = "D:\\test\\Ljy\\TXT";
		int movieNum = 2;
	    @Override  
	    public void run() {  
/////////////////正在热映/////////////////////////
	    	NowMovie nm = new NowMovie();
	    	movieList = nm.getMovieData(movieNum, "kunming");
	    	String[] movieName = (String[])(movieList.get(0));
	    	String[] movieScore = (String[])(movieList.get(1));
	
	    	File file =new File(currentFilePath + "\\MD-AutoData.txt");
	    	if(!file.exists()){
	    		try {
					file.createNewFile();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	    	}
	    	FileWriter fileWritter = null;
			try {
				fileWritter = new FileWriter(currentFilePath + "\\MD-AutoData.txt",true);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
    		SimpleDateFormat sysTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//设置日期格式
    		BufferedWriter bufferedWriter = new BufferedWriter(fileWritter);
	    	try {
	    		for(int i=0; i<movieName.length; i++){
	    		//System.out.println((i+1) + ".电影名称：" + movieName[i]);
	    		//System.out.println("豆瓣评分：" + movieScore[i]);
	    		//System.out.println();
	    			System.out.println(sysTime.format(new Date()) + "  电影名称：" + movieName[i] + ",  " + "豆瓣评分：" + movieScore[i] + "\n");
	    			bufferedWriter.write(sysTime.format(new Date()) + "  电影名称：" + movieName[i] + ",  " + "豆瓣评分：" + movieScore[i]);
	    			bufferedWriter.newLine();
	    		}	
	    		bufferedWriter.newLine();
	    	} catch (IOException e) {
	    		// TODO Auto-generated catch block
	    		e.printStackTrace();
	    	}finally{
	    		try {
	    			if (bufferedWriter != null) {
	    				bufferedWriter.flush();
	                    bufferedWriter.close();
	                    fileWritter.close();
	                }
	             } catch (IOException ex) {
	                ex.printStackTrace();
	             }
	    	}
	    }
}  
